### ISSUE TITLE
Using Sharp 0.33.2 on Vercel

### ISSUE THREAD

**Issue by rochajulian** [withastro/astro#10297]
### Astro Info

```block
Astro                    v4.2.5
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/partytown
                         @astrojs/sitemap
                         @astrojs/svelte
                         @astrojs/react
                         @astrojs/tailwind
```

### Describe the Bug

Hey guys! Working on an Astro project (v4.2.5) that uses Sharp (v.0.33.2). I am deployed on Vercel without build errors "except" the ones below, but when I try to use the part of the project that uses sharp, I get this console log on Vercel:

### Vercel build logs:
```
18:18:29 [build] Waiting for integration "@astrojs/vercel/serverless", hook "astro:build:done"...
[@astrojs/vercel] The module "@img/sharp-wasm32/versions" inside the file "/vercel/path0/node_modules/sharp/lib/utility.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-/package" inside the file "/vercel/path0/node_modules/sharp/lib/sharp.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-dev/include" inside the file "/vercel/path0/node_modules/sharp/lib/libvips.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-dev/cplusplus" inside the file "/vercel/path0/node_modules/sharp/lib/libvips.js" couldn't be resolved. This may not be a problem, but it's worth checking.
```

### Console log tab on Vercel: 
```
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/var/task/vercel/path0/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at exports.b (/opt/node-bridge/chunk-5UAC7W5H.js:1:1142)
    at /opt/node-bridge/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1809)
    at e.<computed>.L._load (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1413)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
```

So i can't use my project the way that I want because sharp doesn't work... 😦
I did research and found this GitHub issue on Sharp: https://github.com/lovell/sharp/issues/3870

Seems like it's a Vercel issue that effected Next.js too. Seems like Next.js released a fix but Astro hasn't gotten that yet (if that's what it needs)

In said issue, people say that downgrading to 0.32.6 for now is what works and that's true. If i downgrade to 0.32.6 then Vercel has no issues but then I have issues locally 😭😭😭 See this GitHub issue that i opened with Sharp's repo: https://github.com/lovell/sharp/issues/4016

Not sure how to move forward now with this deployment other than moving to Netlify or something. But I'd really like to stick with Vercel, any help? I'm happy to provide any more info for anyone, just lmk!

I won't create a Stackblitz for this issue due to the issue being on Vercel. Locally, everything works well in Sharp 0.33.2. 

### What's the expected result?

To be able to use Sharp on my Vercel deployment without getting the error that i mentioned.

### Link to Minimal Reproducible Example

[https://github.com/rochajulian/astro-sharp](https://github.com/rochajulian/astro-sharp)

[https://astro-sharp.vercel.app/](https://astro-sharp.vercel.app/)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
Could you create a minimal GitGub repo so this issue can be investigated?

**Comment by Boston343** [comment]
I'm not sure if this will solve your issue (I deploy on Netlify), but here's a potential fix that worked with me before. The problem for me was that conflicting sharp references (from astro:assets and astro-compress) didn't work on linux, which is how Netlify builds. So my solution was:

1. Uninstall sharp if you've manually installed it in your project
2. Add an override in your package.json file like below

```json
"overrides": {
  "sharp": "^0.33.0"
}
```

**Comment by florian-lefebvre** [comment]
In the first issue you mentioned, it states `@vercel/nft` should be at least `0.26.1`. Looks the vercel integration uses a lower version: https://github.com/withastro/astro/blob/main/packages%2Fintegrations%2Fvercel%2Fpackage.json#L55.

We can't say for sure without a minimal reproduction tho!

**Comment by rochajulian** [comment]
Hi everyone, thanks for all your responses. I've set up a public GitHub repo with a minimal reproduction of this issue. I've also deployed it to Vercel to test if I'm getting the same errors and I am. If you guys clone my repo and quickly deploy it, you'll also see them. 

[https://github.com/rochajulian/astro-sharp](https://github.com/rochajulian/astro-sharp)

[https://astro-sharp.vercel.app/](https://astro-sharp.vercel.app/)

Let me know how else I can help for this. Apologies for not having done this at the start.

**Comment by florian-lefebvre** [comment]
No worries! Thanks for providing one

**Comment by lovell** [comment]
I took a quick look and agree with @florian-lefebvre 's comment in https://github.com/withastro/astro/issues/10297#issuecomment-1974733182 that upgrading the version of `@vercel/nft` in Astro will include the fix for Vercel deployments.

**Comment by florian-lefebvre** [comment]
Looks like `@vercel/nft` is not the issue

**Comment by matthewp** [comment]
@florian-lefebvre did you try upgrading it and the issue persists?

**Comment by florian-lefebvre** [comment]
I created a PR for a preview release with `@vercel/nft` updated to latest. The OP used this version and reported it didn't work (same error as reported initally)

**Comment by florian-lefebvre** [comment]
iirc OP has a npm lockfile indeed! @rochajulian can you check this link?

**Comment by rochajulian** [comment]
Hey guys, just read it and tried my best to understand. Seems like people are saying that deleting package-lock.json and node_modules and re-running npm install fixes the issue, though it's more of a workaround for now until npm pushes a fix, am I correct? If so, I'll try doing that on the repro I gave you all and see how it goes. I do wonder though, isn't it not good to delete package-lock.json?

**Comment by lilnasy** [comment]
I haven't looked at the code, but after deploying I see this:

<img width="529" alt="image" src="https://github.com/withastro/astro/assets/69170106/76b94112-0691-4558-9db3-f5ac9fd79f1b">

@rochajulian Does that mean it works?

**Comment by rochajulian** [comment]
> I haven't looked at the code, but after deploying I see this:
> <img alt="image" width="529" src="https://private-user-images.githubusercontent.com/69170106/309866383-76b94112-0691-4558-9db3-f5ac9fd79f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzgzNzIsIm5iZiI6MTcwOTU3ODA3MiwicGF0aCI6Ii82OTE3MDEwNi8zMDk4NjYzODMtNzZiOTQxMTItMDY5MS00NTU4LTlkYjMtZjVhYzlmZDc5ZjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE4NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZGQ5MWVlMGY2ODM0M2ZhMWRlZjQzZjRkMjc2NDM2MTgxNzAxZDlmNDVjMWU3ZjI4NjIxZTFlNWIwOWRhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7SKvFfHpPeKT9wuimU76ZUHUdAqh2bKoNUjWi2Zv8FI">
> 
> @rochajulian Does that mean it works?
> Logs

Yes, that looks perfect! How'd you get it to work??

**Comment by lilnasy** [comment]
These are the commands I ran:

<details>
<summary> 

```
npm why astro
```
```
npm why @vercel/nft
```

</summary>

<img width="473" alt="image" src="https://github.com/withastro/astro/assets/69170106/78dc28ba-bd71-4434-9643-00f2e78a14d7">

</details>

```
npm exec astro build
```
```
npx vercel deploy --prebuilt --prod
```

**Comment by rochajulian** [comment]
> These are the commands I ran:
> 
> ```
> npm why astro
> ```
> 
> ```
> npm why @vercel/nft
> ```
> 
> ```
> npm exec astro build
> ```
> 
> ```
> npx vercel deploy --prebuilt --prod
> ```

Hmmm. So main difference I see between how you did it and I is that I deployed it through Vercel's dashboard instead of the cli tool like you did. I wonder why. If anyone wants me to provide details of a new deployment or something please let me know

**Comment by rochajulian** [comment]
> Can you confirm whether you had the same version of `@vercel/nft` downloaded?
> 
> You should be able to do that by using `npm why @vercel/nft && npm run build` as the build command.

Just ran that command locally and got this:

```
julianrocha@Julians-MacBook-Pro astro-sharp % npm why @vercel/nft && npm run build
@vercel/nft@0.24.4
node_modules/@vercel/nft
  @vercel/nft@"^0.24.3" from @astrojs/vercel@7.3.4
  node_modules/@astrojs/vercel
    @astrojs/vercel@"experimental--vercel-sharp-nft" from the root project

> astro-sharp@1.0.0 build
> astro build

13:04:45 [vite] Forced re-optimization of dependencies
13:04:45 [build] output: "server"
13:04:45 [build] directory: /Users/julianrocha/Library/CloudStorage/Dropbox/Developer/Websites/astro-sharp/.vercel/output/
13:04:45 [build] adapter: @astrojs/vercel/serverless
13:04:45 [build] Collecting build info...
13:04:45 [build] ✓ Completed in 79ms.
13:04:45 [build] Building server entrypoints...
13:04:45 [vite] ✓ built in 534ms
13:04:45 [build] ✓ Completed in 556ms.

 building client (vite) 
13:04:45 [vite] ✓ 25 modules transformed.
13:04:45 [vite] .vercel/output/static/_astro/client.Cx1FBVJX.js     0.61 kB │ gzip: 0.42 kB
13:04:45 [vite] .vercel/output/static/_astro/ImageForm.C0ie4ykM.js  7.24 kB │ gzip: 3.14 kB
13:04:45 [vite] ✓ built in 90ms
13:04:45 
 finalizing server assets 

13:04:45 [build] Rearranging server assets...
13:04:45 [WARN] [@astrojs/vercel/serverless] Your project is being built for Node.js 20 as the runtime, which is currently in beta for Vercel Serverless Functions.
13:04:45 [@astrojs/vercel/serverless] Bundling function ../../_functions/entry.mjs
[@astrojs/vercel] The module "@img/sharp-wasm32/versions" inside the file "/Users/julianrocha/Library/CloudStorage/Dropbox/Developer/Websites/astro-sharp/node_modules/sharp/lib/utility.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-/package" inside the file "/Users/julianrocha/Library/CloudStorage/Dropbox/Developer/Websites/astro-sharp/node_modules/sharp/lib/sharp.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-dev/include" inside the file "/Users/julianrocha/Library/CloudStorage/Dropbox/Developer/Websites/astro-sharp/node_modules/sharp/lib/libvips.js" couldn't be resolved. This may not be a problem, but it's worth checking.
[@astrojs/vercel] The module "@img/sharp-libvips-dev/cplusplus" inside the file "/Users/julianrocha/Library/CloudStorage/Dropbox/Developer/Websites/astro-sharp/node_modules/sharp/lib/libvips.js" couldn't be resolved. This may not be a problem, but it's worth checking.
13:04:46 [build] Server built in 1.26s
13:04:46 [build] Complete!
```

**Comment by lilnasy** [comment]
So your deployments haven't been using the new version, and it's still possible florian's update helped.

**Comment by rochajulian** [comment]
> So your deployments haven't been using the new version, and it's still possible florian's update helped.

I wonder if someone who clones my reporo and deploys it using the Vercel dashboard will also see this issue. You've made it clear that using the cli for this works which is great, but I'm left wondering what about the Vercel dashboard approach?

**Comment by lilnasy** [comment]
I would be surprised if that makes a difference.

**Comment by lilnasy** [comment]
Overriding `@vercel/nft` back to the version you have was sufficient to reintroduce an error. It's the only factor.

Great work, @florian-lefebvre! Thanks for the help, @lovell!

**Comment by rochajulian** [comment]
I'm really not sure what I'm doing wrong here then. I just tried to run the exact commands that you did initially (just to see mine and yours side by side). I do see the discrepancies between, for example, this line of my output `peer astro@"^4.2.0" from @astrojs/vercel@7.3.4` vs yours but I'm not sure how to get mine like yours. The exact code that I am using right now is in this repro: [https://github.com/rochajulian/astro-sharp (https://github.com/rochajulian/astro-sharp).

 Here's a screenshot of the entire output like you gave me: 

![CleanShot 2024-03-04 at 14 28 37@2x](https://github.com/withastro/astro/assets/73362783/b195225c-3e4c-4d0f-a325-173963fc03f8)

**Comment by florian-lefebvre** [comment]
If that can help you, I had to run `npm install --os=linux --cpu=x64 sharp` as well (but I'm on window so who knows)

**Comment by rochajulian** [comment]
Thanks everyone for the prompt fix. I figured out why it wasn't working on my end and will share here to clear things up. 

When I updated the package I followed these steps from Florian:

> - "@astrojs/vercel": "your-current-version",
> + "@astrojs/vercel": "experimental--vercel-sharp-nft",
> 
> Then run npm install and redeploy

What I have tried just now instead was run `npm uninstall @astrojs/vercel` and then `npm i @astrojs/vercel@experimental--vercel-sharp-nft`

Now that line of my package.json looks like this:

- "@astrojs/vercel": "experimental--vercel-sharp-nft",
+ "@astrojs/vercel": "^0.0.0-vercel-sharp-nft-20240303150417",

After having done this, my `npm why astro` and such commands look identical to lilnasy. The repro now works locally and on Vercel after I pushed these changes and redeployed.

Apologies for any confusion, that fix works great. I just oddly had my package.json different that everyone else's.
