### ISSUE TITLE
Server Islands not cacheable

### ISSUE THREAD

**Issue by JannikWempe** [withastro/astro#12975]
### Astro Info

```block
Astro                    v5.1.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             none
```

### Describe the Bug

Server islands can't be cached effectively. Yes, you can use cache headers and your CDN will cache it.

BUT on `server` mode. The `p` query param of the auto-generated server island URL will change with every request. (The `p` param should be stable using `static` output but I think there are use cases for server islands in server mode (e.g. different cache durations)).

Here is a screenshot from my personal page showing two requests in the network tab:
![image](https://github.com/user-attachments/assets/a8ca399b-7bc3-4813-a5ab-f846ec721fbf)

Note that the `p` param changes between requests. You can check it out [here](https://wempe.dev) if you want (note that I configured CloudFront to ignore the `p` param for caching).

So the CDN would have to ignore the `p` param but that would result in another issue. The `p` param contains the encrypted props that are passed to the server island component. Ignoring the `p` param for caching would result in server islands with different props sharing the same cache. That would not work...

So currently you can only choose between:
- not caching (because of changing `p`)
- caching, but potentially sharing cache between components that have different props passed to them

## Why does that happen?
`p` changes between requests because the `iv` that is used for encryption is random (which it probably should be for strong encryption). [See here](https://github.com/withastro/astro/blob/d48683698eed62676140bf6d0a9d1d587c3364b6/packages/astro/src/core/encryption.ts#L89-L90).

### What's the expected result?

One idea to prevent the issue:
Add another query param that is a hash of the passed props. The same props would result in the same generated hash.

With that, the CDN could ignore `p` and the caching would work as expected because the new query param would be different for different props and thus not sharing the same cache for them anymore.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s2hf8p8k-4ntncmcw

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
Please update your reproduction, there's no `p` prop provided to the island

**Comment by JannikWempe** [comment]
> Please update your reproduction, there's no `p` prop provided to the island

I am not talking about a `p` prop, but the generated `p` query param that is used in the auto-generated `_server-islands/` prefixed path (see my screenshot).

`p` is changing on every request, even if you don't pass any props. That is why it can't be cached.

**Comment by ematipico** [comment]
it seems this is being addressed here https://github.com/withastro/astro/pull/12956

can you confirm?

**Comment by ematipico** [comment]
Closing as duplicate of https://github.com/withastro/astro/issues/12949

**Comment by JannikWempe** [comment]
That is related, for sure. But it looks like it is just about server islands without any props being passed to it.

What about a server island that I pass props to? How should I cache those?

For that reason, I don't think this is a duplicate...

**Comment by ematipico** [comment]
The reproduction and issue talk about "no props" - as I was corrected, but now you bring up server islands with props.

**Comment by ematipico** [comment]
The reproduction and issue talk about "no props" - as I was corrected, but now you bring up server islands with props.

**Comment by JannikWempe** [comment]
I am talking about props in general from the beginning 🤔

![image](https://github.com/user-attachments/assets/c0c1ac69-03e2-437b-b404-74f6ff8bfcc7)


The point is: the same server island should be able to use the same props.

```astro
<!-- these should share a cache -->
<ServerIsland server:defer /> <!-- same props as next line (no props at all) -->
<ServerIsland server:defer /> <!-- same props as previous line (no props at all) -->

<!-- these should share another cache -->
<ServerIsland server:defer something="test" /> <!-- same props as next line -->
<ServerIsland server:defer something="test" /> <!-- same props as previous line -->
```

I am sorry if that wasn't clear enough, I'll update the reproduction.

**Comment by ematipico** [comment]
I believe Astro doesn't check if props are static or not, or even if their values are shared across islands. It's possible we could actually improve that

**Comment by kaytwo** [comment]
My workaround for this issue is to use this pattern: https://docs.astro.build/en/guides/client-side-scripts/#pass-frontmatter-variables-to-scripts

along with Astro sessions that hold any sensitive user data server side so it doesn’t have to get passed directly back to the server as a prop.

Can you say a bit more about your use case? Are the props passed into the server rendered component dynamic for some reason? Where does that dynamism come from? If it comes from the server, you should be able to pass the data in the body instead of the props like above (much easier to just interpolate into the component if it doesn’t need to be accessible from the client side js). If it’s coming from the client side (like a “who is logged in” indicator), the server should also know that, or if you’re eg using a react component you can update it on client side render with a useEffect.

**Comment by datner** [comment]
The case is mostly for caching server islands in something like a CDN in an e-commerce scenario.
Say you have a list 
```ts
declare const items: string[] // <- dynamic, not static
```
```ts
{items.map(it => <Component server:defer item={it} />)}
```
This would render a dynamic list of items. As people have said, you can denote cache requests by specific query parameters in your CDN provider, and it's clear that currently, caching by `p` is moot.
However, in e-commerce applications, this caching can be of vital importance. Invalidating the entire storefront to change the price of a single item is nonsensical. (Dumping your entire database into memory and rendering every single storefront and every page you host from scratch on every typo someone makes it even more absurd, so SSG is irrelevant)
The concerns raised by @kaytwo are valid, but so are the concerns of the users and their choices rather than the framework. That is to say, keeping the `p` query param impenetrable is fine, but maybe adding some way to attach a stable query param defined by the user explicitly would go a long way.
```ts
{items.map(it => <Component server:defer server:query={it} item={it} />)}
```
would create a `?p=XXXXXXX&ck=abc123` (`ck` as in `cache-key` or whatever)

Yes, this takes a bite out of the 2048-byte limit, but considering that the point is caching through a CDN, where even responses to `POST` requests can be cached, this is basically a non-issue.

Basically, the mental model shift is from a server island holding dynamic information unique to the specific user viewing a page to a server island holding dynamic information unique **to itself** regardless of user _or_  page.
The general use case is not to be fully SSG, so you don't need to deploy the app multiple times per second and not be fully SSR, so you don't just stress-test your backend on how good it is with massive concurrency, pseudo-ISR if you will.

**Comment by AirBorne04** [comment]
Hi,

sorry I forgot about this issue, we have had a discussion on the https://github.com/withastro/adapters/issues/498 repo about this behavior and found a work around for it. But it has raised a question about the build `manifest`

# working scenario (workaround)
If the project is configured with `output="server"` and the page referring to a server island prerenders (e.g. `export const prerender=true`) the `p` query param will be static and therefore the page will cache and work as expected.

# sometimes working scenario
If the project is configured with `output="static"` and an adapter has been installed than some deployments (e.g. nodejs and vercel ) will fail the request to the server island. Some digging revealed that those adapters do depend on the `manifest` which is not including server island routes when `output="static"` is set.
Other adapters (e.g. Cloudflare) work because it does not rely on the manifest for configuring dynamic routes.

# proposal
Due to the notion that server islands will not work without adapter installed (why would they?) than the dynamic server island route should be included in the `manifest` so it works across those adapters relying on them.

**Comment by AirBorne04** [comment]
this seems to be related to the issue at hand https://github.com/withastro/astro/issues/12744

**Comment by kaytwo** [comment]
Not worth another issue but: because of how component-level css scoping works, the "enable caching for propless server islands" solution breaks when using scoped css on an ancestor, as that implicitly adds a `data-cid-XXXXXXX` prop to child components.

I really think it's worth it to investigate using an `Astro-Component-Props:` header to deliver the (encrypted) props, and keep a deterministic hash of the props in the query string. This should support both the "browser cache" use case and the "CDN cache" use case, and while it does allow a known plaintext attack, that's very different from full props leaking in query strings.

Happy to code it up if people believe it's a reasonable way forward.

**Comment by dbismut** [comment]
Hey, thanks for this fantastic framework. Is there a plan to tackle this issue at some point? Not being able to cache Server Components would considerably hinder their adoption with high traffic website IMHO.

**Comment by vitalijalbu** [comment]
Would be great to have caching in everything, not only islands😊

**Comment by matthewp** [comment]
Has anyone looked into why it changes with every request? I implemented this code and there's nothing I know of that should cause that, but I'm perhaps misremembering something.

I suppose it's likely the encryption, but I don't know enough about this to know for sure. Here's the relevant code: https://github.com/withastro/astro/blob/a125a14c51c8f66fef0b582e5daf90ff02fce821/packages/astro/src/runtime/server/render/server-islands.ts#L163-L166

**Comment by DevMozgus** [comment]
Is this currently still an issue? Would love to use server islands but need caching as well

**Comment by matthewp** [comment]
No new activity since July last year, so closing.

**Comment by onvlt** [comment]
It's unfortunate to see this issue closed as "completed", because the problem persists. I think it should at least remain opened for record.

Due to this bug, [documentation](https://docs.astro.build/en/guides/server-islands/#caching) is straight up misleading, claiming:

> The data for server islands is retrieved via a GET request, passing props as an encrypted string in the URL query. This allows caching data with the [Cache-Control HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cache-Control) using standard Cache-Control directives.

But if query param changes with every request (even in absence of any props passed), this makes caching impossible.

If maintainers do not intend to fix this, the documentation should be at least corrected.
