### ISSUE TITLE
Error hydrating: picocolors does not provide an export named 'default'

### ISSUE THREAD

**Issue by rktyt** [withastro/astro#14615]
### Astro Info

```block
Astro                    v5.15.1
Vite                     v6.4.1
Node                     v20.19.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node (v9.5.0)
Integrations             @astrojs/react (v4.4.0)
```

### Describe the Bug

After updating from 5.14.8 to 5.15.1, an error started appearing in the browser console.

> [astro-island] Error hydrating /src/components/Header.tsx SyntaxError: The requested module '/node_modules/picocolors/picocolors.browser.js?v=70bfba13' does not provide an export named 'default' (at endpoint.js?v=70bfba13:1:8)

I’m checking it with `npm run dev`.

#### Updates

~~Essentially, is this the same issue as https://github.com/withastro/astro/issues/14577 ?~~

It seems to occur even when using images other than SVG, such as PNG, in a client component.

### What's the expected result?

No errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v3vslw94?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by florian-lefebvre** [comment]
cc @delucis probably a regression from #14598

**Comment by delucis** [comment]
Oh, weird, why is that being used in the browser?! (Picocolors does support browser environments, but super weird that it's used at all.)

Just catching a train but can take a look in a bit. May be worth a revert in the meantime to be safe if someone has a minute?

**Comment by delucis** [comment]
Looks like picocolors isn't ESM-only and the Common JS `module.exports` usage in their browser bundle is breaking stuff. There are a couple of issues in the repo that haven't been responded to, e.g. https://github.com/alexeyraspopov/picocolors/issues/70

Sorry for not testing this more thoroughly, I'd expected issues like this to be picked up by our build and test suites.

We should 

1. Revert for now
2. Try to figure why this is pulled in at all. It presumably means folks are currently bundling `kleur` for this usage which is not good 😄

**Comment by delucis** [comment]
Just leaving a note to say I do think this is basically related to #14577 — the SVG import pulls in the entire server runtime, which in this case happens to include terminal text styles, and therefore picocolors. I’m guessing at build time it’s often OK because stuff gets tree-shaken out. Still, I wonder if we can try to isolate the assets from the server runtime a bit to make this less fragile.

**Comment by ematipico** [comment]
I don't think we should revert the change, and I think we should fix the issue you linked.

As you said, technically we're doing something wrong when bundling stuff, and that's not the logging library :)

**Comment by delucis** [comment]
Seems tricky to solve 100% even if we can mitigate things a bit. 

I started by looking at the assets plugin thinking “If the SVG is imported in a client component, we can avoid attaching the Astro component instance”. But I don’t think it quite works like that: in Vite/Rollup we can try to work out what kind of file is doing the importing and decide how to resolve that, but we can’t do that on per-usage basis. Once a module is loaded, it is loaded for all usages. So we could detect that an SVG has a dependent that is JSX/TSX/Svelte/Vue, but if the SVG is used in both Astro and one of those, we’d need to include the Astro component instance for both.

So mitigations we could consider:

1. (easy) — reduce what [`src/assets/runtime.ts`](https://github.com/withastro/astro/blob/8ebc0d79756a73741ac01c4a09a864b60bb7207f/packages/astro/src/assets/runtime.ts) imports by not importing from the `runtime/server/index.js` barrel file
2. (more work) — audit and refactor those direct imports to reduce this further
3. (not sure if feasible or worth it) — implement logic in [`src/assets/vite-plugin-assets.ts`](https://github.com/withastro/astro/blob/8ebc0d79756a73741ac01c4a09a864b60bb7207f/packages/astro/src/assets/vite-plugin-assets.ts) to only attach the component if we detect usage in `.astro`

Finally, I guess in theory a refactor of the SVG component feature _might_ be possible to avoid this? But I’m not 100% sure of the ideal design. In theory Astro’s renderer could contain the logic for rendering an SVG `ImageMetadata` object instead of attaching an Astro component to the metadata object.

**Comment by delucis** [comment]
I take the above back, the fix _may_ in fact be simple? See #14623.

Want to do a bit more testing, but appears to work.

**Comment by JoostKersjes** [comment]
Not sure this is useful feedback, but I'm still seeing this `Error hydrating: picocolors does not provide an export named 'default'` error on our fully static website project after locally upgrading to `astro@5.15.2`.

**Comment by delucis** [comment]
Hi @JoostKersjes! Could you share a reproduction where this happens? At least for the reproduction shared in this issue, the error no longer occurs with 5.15.2, so we’d need some project where we can see the error still happening to figure out why.

**Comment by JoostKersjes** [comment]
@delucis Yes I'm currently working on diagnosing which of our Vue components are breaking and figuring out why. Should I just open a new issue if I have a reproduction? We're using `shadcn-vue`, so I'll likely be digging in that library for the next little while.

**Comment by delucis** [comment]
Yeah a new issue would be super helpful, thanks! Definitely possible my fix didn’t cover all scenarios, I guess. Sorry for the inconvenience.

**Comment by somethingxdev** [comment]
> Yeah a new issue would be super helpful, thanks! Definitely possible my fix didn’t cover all scenarios, I guess. Sorry for the inconvenience.

I also keep getting this error when using the client-side React component.

**Header.tsx**
```js
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle } from '@/components/ui/navigation-menu';
import { cn } from '@/lib/utils';
import { getAssetURL } from '@/directus';
import { getRelativeLocaleUrl } from 'astro:i18n';

interface MenuItem {
  label: string;
  description?: string;
  link: string;
  icon?: string;
  external?: boolean;
  target?: string;
}

interface MenuGroup {
  label: string;
  items?: MenuItem[];
  href?: string;
  isHeader?: boolean;
}

interface HeaderProps {
  menuItems: MenuGroup[];
  currentLocale?: string;
  latestBlogPost?: any;
}

export function Header({ menuItems, currentLocale = 'en', latestBlogPost }: HeaderProps) {
  return (
    <NavigationMenu className="w-full">
      <NavigationMenuList className="flex-col items-start gap-3 md:flex-row md:items-center md:justify-center">
        {menuItems.filter((item) => item.isHeader === true).map((item, index) => (
            <NavigationMenuItem key={index}>
              {item.items ? (
                <>
                  <NavigationMenuTrigger className="font-medium text-foreground hover:text-secondary data-[popup-open]:text-secondary">{item.label}</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <div className="flex items-start gap-5 p-3">
                      <ul className={cn('grid w-full items-start gap-3', index === 0 ? 'grid-cols-3' : 'grid-cols-2')}>
                        {item.items.map((subItem, subIndex) => (
                          <ListItem key={subIndex} title={subItem.label} href={getRelativeLocaleUrl(currentLocale, subItem.link)} target={subItem.target}>
                            {subItem.description}
                          </ListItem>
                        ))}
                      </ul>
                      {index === 1 && (
                        <div className="max-w-[340px] shrink-0 rounded-2xl bg-neutral p-3">
                          <div className="mb-3 border-b border-neutral-100/30 pb-3">
                            <a href="#" className="flex flex-col items-end gap-2 gap-3 font-semibold text-white hover:text-secondary">
                              <img src={getAssetURL(latestBlogPost.data.thumbnail.filename_disk)} alt={latestBlogPost.slug} className="h-30 w-full rounded-xl object-cover" />
                              <p>{latestBlogPost.data.translations.title}</p>
                            </a>
                          </div>
                        </div>
                      )}
                    </div>
                  </NavigationMenuContent>
                </>
              ) : (
                <NavigationMenuLink href={item.href} className={cn(navigationMenuTriggerStyle(), 'font-medium text-foreground hover:text-secondary')}>
                  {item.label}
                </NavigationMenuLink>
              )}
            </NavigationMenuItem>
          ))}
      </NavigationMenuList>
    </NavigationMenu>
  );
}

function ListItem({ title, children, href, target, ...props }: React.ComponentPropsWithoutRef<'li'> & { href: string; target?: string }) {
  return (
    <li {...props}>
      <NavigationMenuLink href={href} target={target} className="flex max-w-[400px] flex-col gap-1 rounded-md p-3">
        <div className="text-base font-semibold text-foreground">{title}</div>
        <p className="line-clamp-2 text-sm text-content">{children}</p>
      </NavigationMenuLink>
    </li>
  );
}

export default Header;
```
**navigation-menu.tsx**

```js
import * as React from 'react';
import { NavigationMenu as BaseNavigationMenu } from '@base-ui-components/react/navigation-menu';
import { cva } from 'class-variance-authority';
import { ChevronDownIcon } from 'lucide-react';

import { cn } from '@/lib/utils';

function NavigationMenu({ className, children, ...props }: React.ComponentProps<typeof BaseNavigationMenu.Root>) {
  return (
    <BaseNavigationMenu.Root data-slot="navigation-menu" className={cn('min-w-max', className)} {...props}>
      {children}
      <NavigationMenuViewport />
    </BaseNavigationMenu.Root>
  );
}

function NavigationMenuList({ className, ...props }: React.ComponentProps<typeof BaseNavigationMenu.List>) {
  return <BaseNavigationMenu.List data-slot="navigation-menu-list" className={cn('relative flex items-center gap-1', className)} {...props} />;
}

function NavigationMenuItem({ ...props }: React.ComponentProps<typeof BaseNavigationMenu.Item>) {
  return <BaseNavigationMenu.Item data-slot="navigation-menu-item" {...props} />;
}

function NavigationMenuIcon({ ...props }: React.ComponentProps<typeof BaseNavigationMenu.Icon>) {
  return <BaseNavigationMenu.Icon data-slot="navigation-menu-icon" {...props} />;
}

const navigationMenuTriggerStyle = cva(
  "inline-flex w-max items-center justify-center gap-1.5 font-medium hover:text-secondary focus:text-secondary data-[popup-open]:secondary outline-none transition-[color,box-shadow] focus-visible:ring-3 select-none no-underline [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0"
);

function NavigationMenuTrigger({ className, children, ...props }: React.ComponentProps<typeof BaseNavigationMenu.Trigger>) {
  return (
    <BaseNavigationMenu.Trigger data-slot="navigation-menu-trigger" className={cn(navigationMenuTriggerStyle(), className)} {...props}>
      {children}
      <NavigationMenuIcon className="transition-transform duration-300 data-[popup-open]:rotate-180">
        <ChevronDownIcon aria-hidden="true" />
      </NavigationMenuIcon>
    </BaseNavigationMenu.Trigger>
  );
}

function NavigationMenuContent({ className, ...props }: React.ComponentProps<typeof BaseNavigationMenu.Content>) {
  return <BaseNavigationMenu.Content data-slot="navigation-menu-content" className={cn('w-full p-2 md:w-auto', className)} {...props} />;
}

function NavigationMenuLink({ className, ...props }: React.ComponentProps<typeof BaseNavigationMenu.Link>) {
  return (
    <BaseNavigationMenu.Link
      data-slot="navigation-menu-link"
      className={cn(
        "flex flex-col gap-1.5 transition-all outline-none hover:bg-neutral hover:text-foreground focus:bg-accent focus:text-accent-foreground focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:outline-1 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",
        className
      )}
      {...props}
    />
  );
}

function NavigationMenuViewport({ className, ...props }: React.ComponentProps<typeof BaseNavigationMenu.Popup>) {
  return (
    <BaseNavigationMenu.Portal data-slot="navigation-menu-portal">
      <BaseNavigationMenu.Positioner
        sideOffset={20}
        align="center"
        positionMethod="fixed"
        className="z-[200] h-[var(--positioner-height)] w-[var(--positioner-width)] max-w-[var(--available-width)] origin-[var(--transform-origin)] duration-300"
        data-slot="navigation-menu-positioner"
      >
        <BaseNavigationMenu.Popup
          className={cn(
            'z-[200] h-[var(--popup-height)] w-[var(--popup-width)] origin-[var(--transform-origin)] overflow-hidden rounded-md border border-neutral bg-popover text-foreground shadow-md duration-300 data-closed:animate-out data-closed:fade-out-0 data-closed:zoom-out-95 data-open:animate-in data-open:fade-in-0 data-open:zoom-in-95',
            className
          )}
          data-slot="navigation-menu-popup"
          {...props}
        >
          <BaseNavigationMenu.Viewport data-slot="navigation-menu-viewport" />
        </BaseNavigationMenu.Popup>
      </BaseNavigationMenu.Positioner>
    </BaseNavigationMenu.Portal>
  );
}

export { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink, navigationMenuTriggerStyle };
```

**Comment by faisalagood** [comment]
@delucis 

> Yeah a new issue would be super helpful, thanks! Definitely possible my fix didn’t cover all scenarios, I guess. Sorry for the inconvenience.

I am able to reproduce this but it's based on StudioCMS with all the latest dependencies. Is this okay? I have not found a way to trigger it through Astro alone.

**Comment by JoostKersjes** [comment]
Thanks @faisalagood! The `astro:i18n` is also what is causing me problems.

**Comment by KonstantinKliukhin** [comment]
I still have this issue even with latest version: "astro": "^5.15.4".
What is fix status?

**Comment by florian-lefebvre** [comment]
@KonstantinKliukhin see #14692 for a workaround
