### ISSUE TITLE
🐛 BUG: Junky page load/reload

### ISSUE THREAD

**Issue by Rolanddoda** [withastro/astro#2147]
### What version of `astro` are you using?

^0.21.11

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I just installed a fresh project with pnpm "portfolio-svelte" and then run the `dev` script. See the behavior on pressing re-load:

https://www.loom.com/share/c8235a43513d4d2fb3d168438428ae3c

The "Link to Minimal Reproducible Example" doesn't seem to have this issue, but it does have a similar issue when reloading/refreshing.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/snowpackjs/astro/tree/latest/examples/portfolio?on=stackblitz

**Comment by jonathantneal** [comment]
@Rolanddoda, would you be able to share some screenshots of what you’re seeing? In the off chance this is an issue fixed in the last week, I’d like to know what to look for. I can’t figured out what "junk" means. 😅

**Comment by Rolanddoda** [comment]
@jonathantneal screenshots ? I have posted a video above!

**Comment by Go-Merk** [comment]
> @jonathantneal screenshots ? I have posted a video above!

I don't think this is an issue, did you tested uploading the project on a server to see if this continues?  I would rather say this is the standard behavior of local files on a dev server, everything is either cached or available locally so, there is nothing like "order of load", try uploading on netlify, vercel, and see if the issue will be there.

**Comment by Rolanddoda** [comment]
>I would rather say this is the standard behavior of local files on a dev server

@Go-Merk you are probably right. If so, I don't have any problem if this issue is closed. However, I am going to take a look this weekend to see if the issue persists in the newer version.

**Comment by Rolanddoda** [comment]
I tried the last version `0.21.13` and I am still getting that behavior.

**Comment by Go-Merk** [comment]
Did you actually tried to upload your project in someplace just to test? @Rolanddoda

**Comment by Rolanddoda** [comment]
@Go-Merk this issue is about local environment, and probably as you mentioned it's because that is a standard behavior of local files. And if that's the case, then I guess this issue should be closed.

**Comment by tony-sull** [comment]
Closing this issue as it looks like this was tracked down to a local environment setup.  If you run into this again in the latest version of Astro please open another issue :+1:
