### ISSUE TITLE
🐛 BUG: Astro import.meta types conflict with vite/client

### ISSUE THREAD

**Issue by ratorx** [withastro/astro#2297]
### What version of `astro` are you using?

0.22.3

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Astro defines types for `import.meta` for the language server. However these types conflict with the `vite/client` types.

Since Astro defines `import.meta` types only for the astro language server, they are not applied in regular typescript files (only Astro components), which causes an error (e.g. `import.meta.env` not found).

If you try to fix this problem by including `vite/client` in `compilerOptions.types` in `tsconfig.json`, the Typescript files happily typecheck, but all astro components start complaining about conflicting types.

My current workaround is to include `@astrojs/language-server/astro` in `tsconfig.json`.

Couple of requests:
Would it possible to fix Vite/whatever specific typings for the entire project without manual configuration? A simple fix might be to manually add a Astro specific declarations to the example `tsconfig.json`. This would be a manual fix for existing projects, but an automatic one for new ones. However, ideally the global types would get included automatically for all files (not just Astro ones via the language server).

Would it possible to just use the upstream `vite/client` types for the Astro language server? The types seem compatible enough to not cause issues for now, but having the inconsistency seems undesirable.

## Reproduction

Run `astro check` on the stackblitz project.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ardmcn

**Comment by matthewp** [comment]
Thanks, we have fixed this in the language server and now just need to update astro.

**Comment by lakano** [comment]
Hi @matthewp 
Since I've moved from 0.21.13 to 0.22.*, I have very weird bug if I'm just using import.meta.env, it's may be related to this closed bug, I've tried also with the last version 0.22.6 but it's still there... but as you said this need to be also fixed in Astro, may be I just need to wait. Could you confirm it's not yet fixed in Astro please? Otherwise I'll open a new issue to report all details. Thanks

**Comment by matthewp** [comment]
The type conflict that you see in VSCode was fixed, yes.
