### ISSUE TITLE
🐛 BUG: doesn't react when I change files

### ISSUE THREAD

**Issue by 7flash** [withastro/astro#2728]
### What version of `astro` are you using?

^0.23.7

### What package manager are you using?

pnpm

### What operating system are you using?

Windows 11

### Describe the Bug

When I make change to .astro file I am expecting my web browser page to automatically reflect changes, but currently it doesn't happen even after I manually refresh page; it only shows updated page after I manually stop astro process and run "npm start" again

I think the issue is related to using WSL 2.0

### Link to Minimal Reproducible Example

any template works in cloud environment, but not working in my WSL

**Comment by 7flash** [comment]
Found Solution: move project folder to WSL home directory

**Comment by gbizetdev** [comment]
Maybe I'm wrong, but I don't think it's related to WSL. I get same issue on Mac with astro files. And it happens when modifying vanilla js in **<script>** tags and **<style>** tags too.

**Comment by RanRocha** [comment]
It is not working for me also. Using Visual Studio Code on Windows 10.

**Comment by dfghjkjhgr** [comment]
I think it's fixed in `astro@next`

**Comment by dfghjkjhgr** [comment]
Never mind

**Comment by natemoo-re** [comment]
This seems like an old HMR issue? We recently did an overhaul of our HMR handling, but please feel free to re-open if you're still experiencing a problem related to `.astro` files.

**Comment by alfawal** [comment]
@natemoo-re it still exists when running projects from `/mnt`

**Comment by alfawal** [comment]
My issue is Windows <=> WSL related. Symlinks won't fix the issue either.

**Comment by wanjohiryan** [comment]
This is still an issue on WSL @natemoo-re
