### ISSUE TITLE
Config's `base` option producing unexpected asset paths

### ISSUE THREAD

**Issue by HappyTiptoe** [withastro/astro#4229]
### What version of `astro` are you using?

1.0.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Linux (Fedora 36)

### Describe the Bug

At my company, we create websites for clients, and need to be able to host websites at paths which may change. By referencing assets via `./`, this makes the website path agnostic, and doesn't require a rebuild should the path change.

Unfortunately, the `base` option in `astro.config.mjs` is not allowing for such a value, which is causing issues with asset/stylesheet referencing.

## Config

<table><tr><td width="400px" valign="top">

### Config

I have `base` set to `"./"` in my config file. With this, I expect `<link>`s, `<script>`s, and assets to be referenced via `src="./path/to/file"`. However, I'm getting unexpected, inconsistent results.

</td><td><br>

```js
import { defineConfig } from 'astro/config'

/* ... */

export default defineConfig({
  /* ... */
  base: './'
})
```

</td></tr></table>

## Results

<table><tr><td width="400px" valign="top">

### Stylesheet

The stylesheet is referenced by `/assets/...`, which makes me feel that the `base` option isn't being respected at all here. 

However, setting `base: "/foo"`will yield expected results. There seems to be an issue with the preceding `.`.

</td><td><br>

```html
<link
  rel="stylesheet"
  href="/assets/index.be4ae9a2.css" 
/>
```

</td></tr></table>

<table><tr><td width="400px" valign="top">

### Assets

Whether in an Astro component, or a Vue component, my assets are referenced via `src="/./assets/..."`. 

Is the `/` is being prepended because the first character of the path isn't `/`, maybe?

</td><td><br>

```html
<img src="/./assets/image.e23d31cb.jpg">
```

</td></tr></table>

### Link to Minimal Reproducible Example

https://github.com/ebxn/astro-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by andresantiagohellmann** [comment]
Mesmo problema aqui...

**Comment by andresantiagohellmann** [comment]
Did you find any solution? I'm having the same problem here...

**Comment by evan-dunkel** [comment]
I'm having this issue on 1.0.6 too, the discord support channel didn't offer any help either.

**Comment by matthewp** [comment]
@bluwy I'm assigning to you to investigate. It's possible that this is a tricky issue so we might need to talk about it before trying to fix it.

**Comment by bluwy** [comment]
It looks like the codebase is expecting absolute path for the `base`. Relative path handling is tricky to implement since we're constructing a `URL` with the `site` and `base` config, which `base: './'` is basically hidden in a `URL`.

I think this might involve some refactoring to make relative base work, but a partial good news is that Vite has good support for `./` since Vite 3 so that might make some parts easier.

This issue could also be considered a feature request, but I think it has a necessary usecase to live here (?).

**Comment by matthewp** [comment]
We can't really support fully relative paths. If you set your base to `./` we could make the link be `<link rel="stylesheet" href="./assets/index.be4ae9a2.css" />`

And that would work for the `/index.html` page. But for `/about/index.html` it would be wrong. You might say that we could fix it for you to be `../assets/index.be4ae9a2.css` on the about page but it would break on the `/404.html` page.

Also, @bluwy I believe that Vite loads client-side CSS using an absolute path, is that right?

**Comment by HappyTiptoe** [comment]
Interesting. What you've said makes sense to me! I failed to mention that my company produces single pages (so a single html file), so I've never encountered issues with multiple .html files and asset paths. 

I feel it's a case of Astro just not being the right tool for my use-case, in this instance, since Astro seems a lot more tailored to creating full websites rather than single pages - though please correct me if I'm wrong on this!

**Comment by cauboy** [comment]
I'm also having some issue with the `base` property, however, not with a relative but with an absolute path. Here's [my post on Discord](https://discordapp.com/channels/830184174198718474/1035184312124981278/1035184312124981278) regarding my issue:

> I want to proxy traffic from some subfolder of our main server to a SSR Astro project that's hosted as a Cloudflare Page as a low-impact experiment to replace our current stack with Astro. However, I'm having issues and am not sure if I'm going the wrong route or if there are some Astro issues involved.
> 
> For example, I want to proxy all traffic from https://www.example.com/my-astro-app/*  to https://example.pages.dev/*. 
> 
> As I will proxy all requests from `/my-astro-app` to `/` I set the `base` property in `astro.config.mjs` to `base: "/my-astro-app"` 
> 
> But this is only partially doing what I'm expecting:
> 
> -  Images that are imported as follows
>    ```
>    # index.astro
>    import MyImage from './some/path/myimage.jpg`
>    …
>    <img src={MyImage} />
>    …
>    ```
>    end up as `<img src="/my-astro-app/myimage.1d74c9c5.jpg">` in the rendered HTML when opening example.pages.dev. That's what I was expecting.
> 
>  However, that's not the case for all the resources that appear in the rendered HTML. For example:
> 
>  - The main css file is not prefixed. It's `<link rel="stylesheet" href="/assets/index.58739ba0.css">` instead of `<link rel="stylesheet" href="/my-astro-app/assets/index.58739ba0.css">`
> Paths to assets in the css file are also not prefixed, e.g.  it's `background-image:url(/my-background-image.svg);` instead of `background-image:url(/my-astro-app/my-background-image.svg);`
> 
> So I'm wondering: Am I abusing the base property? Is there some bug? Or is there another better way to implement the whole thing.
> 
> I'm happy about any feedback.

**Comment by bluwy** [comment]
> Also, @bluwy I believe that Vite loads client-side CSS using an absolute path, is that right?

If you set the `base` Vite config to `./`, it will be relative.



> And that would work for the `/index.html` page. But for `/about/index.html` it would be wrong. You might say that we could fix it for you to be `../assets/index.be4ae9a2.css` on the about page but it would break on the `/404.html` page.

I'm not sure how this would break for the `404.html`, wouldn't that be built the same way as `index.html` as we generate the relative links correctly? This strategy is currently used in Vite's MPA implementation.

**Comment by wulinsheng123** [comment]
Is the / is being prepended because the first character of the path isn't /, maybe?

How do I understand this？ Could you tell me more？

**Comment by bluwy** [comment]
Ah right that's a valid problem. Perhaps we can auto add `base` tag specifically for `404.html` to make it work, or otherwise it'd be something to document.

**Comment by falco467** [comment]
I think relative base should be supported and documented that absolute documents like the 404.html are not supported with relative base.

I can't think of a case where one can provide an absolute base for the 404 while needing a relative base für everything else. Better provide a warning than constructing this mix of relative and absolute which will break in subtle corner cases.

**Comment by HappyTiptoe** [comment]
> > > Is the / is being prepended because the first character of the path isn't /, maybe?
> > > How do I understand this？ Could you tell me more？
> > 
> > 
> > Hi @wulinsheng123. I don't know anything about the internals of Astro/Vite, but this was just me theorising as to why my asset links were `/./`. Nothing to worry about!
> 
> So you hope your asset links is ‘./‘ right ？

Correct

**Comment by matthewp** [comment]
For those who want `./` to work, this means that if you have a page like `src/pages/foo/bar/boo.astro`, it's going to add a like like `<link rel="stylesheet" href="./assets/something.css">` which is obviously wrong. What is it you want to happen here?

**Comment by matthewp** [comment]
Ok, a couple of updates here:

1. A new patch release (coming out tomorrow) fixes using the base to reference items in your public folder, like `/docs/penguin.png`. This was previously not working and you instead were forced to *omit* the base in dev but not in prod. This is fixed and it now warns you if you do not include the base.
2. I've created a new RFC that seeks to allow Astro to build relative links for thinks like stylesheets and scripts in the build. https://github.com/withastro/rfcs/pull/381

Given those two things are either done or being worked on, there's nothing left in this issue to do so I'm going to close. If you have any other bugs surrounding `base` given how it works today (and not related to that RFC), please file new issues.

Thanks a lot everyone! And please help me champion the RFC, I think this will be a big addition to Astro.

**Comment by falco467** [comment]
Should we reopen this case, since the RFC was cancelled?

**Comment by ixkaito** [comment]
I have published an integration and hope it will be a solution.

https://www.npmjs.com/package/astro-relative-links

**Comment by phocks** [comment]
> I have published an integration and hope it will be a solution.
> 
> https://www.npmjs.com/package/astro-relative-links

Thanks for this. Solved perfectly. Strange that everyone seems to be afraid of relative links these days!

**Comment by kelvin-zhao** [comment]
> I have published an integration and hope it will be a solution.
> 
> https://www.npmjs.com/package/astro-relative-links

Works great! Wonder why this is not considered in the original Astro build?

**Comment by andresantiagohellmann** [comment]
> Publiquei uma integração e espero que seja uma solução.
> 
> https://www.npmjs.com/package/astro-relative-links

THX!

**Comment by petdomaa100** [comment]
I find it really surprising that relative paths are still not a feature in Astro. I'm using it as a static site generator, and sometimes the site ends up deployed under different subpaths, and I'd prefer not to rely on rebuilding every time.

Relying on post‑processing the final build with regexes feels like asking for subtle bugs down the line. I'm not familiar with the internals to know whether this is a missing feature of Astro or Vite, but I'd really like built-in support for relative paths. I understand why the RFC was closed, but I wonder whether the underlying use case could be revisited.
